[package]
name = "git-descendents"
version = "0.1.0"
authors = ["Emily Amanda Bellows"]

[dependencies]
serde = "1"
serde_json = "1"
serde_derive = "1"
failure = "0.1"
git2 = "0.6"
clap = "2.30"
colored = "1.6"
chrono = "0.4"
